default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: localhost
  port: 5432
  database: ai_chatbot_backend_development
  username: postgres
  password: mOd4proJ@23

test:
  <<: *default
  host: localhost
  port: 5432
  database: ai_chatbot_backend_test
  username: postgres
  password: mOd4proJ@23

production:
  primary:
    url: <%= ENV["DATABASE_URL"] %>

  cable:
    url: <%= ENV["DATABASE_URL"] %>

  queue:
    url: <%= ENV["DATABASE_URL"] %>


